{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: pre-install, pre-upgrade, post-delete
    helm.sh/hook-delete-policy: before-hook-creation, hook-failed, hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ include "globalResourceName" (dict "name" "hook-scc" "root" .) }}
runAsUser:
  type: MustRunAsNonRoot
seccompProfiles:
  - '*'
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.resourceNamePrefix }}-post-delete-service-account
  - system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.resourceNamePrefix }}-pre-install-service-account
volumes:
  - csi
  - emptyDir
  - secret
{{- end }}