apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    helm.sh/hook-output-log-policy: hook-failed
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Values.resourceNamePrefix }}-post-delete-job
  namespace: {{ include "namespace" . }}
spec:
  backoffLimit: 0
  template:
    {{- $hookAnnotations := default .Values.pod.annotations .Values.hooks.pod.annotations }}
    {{- $hookLabels := default .Values.pod.labels .Values.hooks.pod.labels }}
    {{- if or $hookAnnotations $hookLabels }}
    metadata:
      {{- with $hookAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $hookLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
      {{- with (default .Values.pod.affinity .Values.hooks.pod.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: true
      containers:
        - args:
            - release-post-delete
            - --api-key-token-file-path
            - {{ include "apiKeyTokenFilePath" . | quote }}
            - --api-url
            - {{ .Values.apiUrl | quote }}
            {{- if .Values.proxyUrl }}
            - --proxy-url
            - {{ .Values.proxyUrl | quote }}
            {{- end }}
          {{- include "containerEnvironmentVariables" . | nindent 10 }}
          image: {{ include "containerImage" . }}
          imagePullPolicy: Always
          name: {{ .Values.resourceNamePrefix }}-post-delete-container
          {{- with (default .Values.pod.resources .Values.hooks.pod.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- include "containerSecurityContext" (dict "securityContext" (default .Values.pod.containers.securityContext .Values.hooks.pod.containers.securityContext)) | nindent 12 }}
          {{- $volumeMounts := print (include "containerCaCertificateVolumeMount" .) "\n" (include "containerSecretsVolumeMount" .) }}
          {{- with trim $volumeMounts }}
          volumeMounts:
            {{- . | nindent 10 }}
          {{- end }}
      {{- with (include "containerImagePullSecretNames" (dict "name" (print .Values.resourceNamePrefix "-post-delete-image-pull-secret") "root" .) | trim) }}
      imagePullSecrets:
        {{- . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      securityContext:
        {{- include "podSecurityContext" (dict "root" . "workloadContext" .Values.hooks.pod.securityContext) | nindent 8 }}
      serviceAccountName: {{ .Values.resourceNamePrefix }}-post-delete-service-account
      {{- with (default .Values.pod.tolerations .Values.hooks.pod.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $volumes := print (include "containerCaCertificateVolume" (dict "name" (include "containerCaCertificateSecretName" (dict "parent" "post-delete" "root" .)) "root" .)) "\n" (include "containerSecretsVolume" (dict "name" (include "apiKeyTokenSecretName" (dict "parent" "post-delete" "root" .)) "root" .)) }}
      {{- with trim $volumes }}
      volumes:
        {{- . | nindent 8 }}
      {{- end }}
---
{{ $apiKeyTokenSecretAnnotations :=
  list
  "helm.sh/hook: post-delete"
  "helm.sh/hook-delete-policy: before-hook-creation, hook-failed, hook-succeeded"
  "helm.sh/hook-weight: \"-1\"" }}
{{ include "apiKeyTokenSecret" (dict "name" (include "apiKeyTokenSecretName" (dict "parent" "post-delete" "root" .)) "root" . "annotations" $apiKeyTokenSecretAnnotations) }}

---
{{ $containerCaCertificateSecretAnnotations :=
  list
  "helm.sh/hook: post-delete"
  "helm.sh/hook-delete-policy: before-hook-creation, hook-failed, hook-succeeded"
  "helm.sh/hook-weight: \"-2\"" }}
{{ include "containerCaCertificateSecret" (dict "name" (include "containerCaCertificateSecretName" (dict "parent" "post-delete" "root" .)) "root" . "annotations" $containerCaCertificateSecretAnnotations) }}
---
{{ $containerImagePullSecretAnnotations :=
  list
  "helm.sh/hook: post-delete"
  "helm.sh/hook-delete-policy: before-hook-creation, hook-failed, hook-succeeded" 
  "helm.sh/hook-weight: \"-10\"" }}
{{ include "containerImagePullSecret" (dict "name" (print .Values.resourceNamePrefix "-post-delete-image-pull-secret") "root" . "annotations" $containerImagePullSecretAnnotations) }}