apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    helm.sh/hook-weight: "-4"
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ include "globalResourceName" (dict "name" "pre-install-crb" "root" .) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "globalResourceName" (dict "name" "pre-install-cr" "root" .) }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.resourceNamePrefix }}-pre-install-service-account
  namespace: {{ .Release.Namespace }}