apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "updater.labels" . | nindent 4 }}
  name: {{ include "updater.globalResourceName" (dict "name" "cr" "root" .) }}
rules:
  - apiGroups: [""]
    resourceNames: ["kube-system"]
    resources: ["namespaces"]
    verbs: ["get"]