apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "updater.labels" . | nindent 4 }}
  name: {{ include "updater.resourceNamePrefix" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: 
      - 
      - admissionregistration.k8s.io
      - apiextensions.k8s.io
      - apiregistration.k8s.io
      - apps
      - autoscaling
      - batch
      - discovery.k8s.io
      - events.k8s.io
      - extensions
      - policy
      - rbac.authorization.k8s.io
      - storage.k8s.io
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]