apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "updater.labels" . | nindent 4 }}
  name: {{ include "updater.resourceNamePrefix" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]