apiVersion: v2
name: tes-traefik
description: Traefik ingress gateway for Tenable Enclave Security (TES)
type: application
version: 1.0.0
appVersion: "3.6.12"

keywords:
  - traefik
  - tes
  - tenable
  - ingress
  - gateway
  - mtls
  - security

maintainers:
  - name: TES Team
    email: tes-team@tenable.com

dependencies:
  - name: traefik
    version: "39.0.7"
    repository: https://traefik.github.io/charts
