admissionController:
  certificateAuthorityOrganizationName: tenable
  containerImagePath: tenable/cloud-security-kubernetes-cluster-admission-controller
  containerImagePullSecrets: []
  pod:
    affinity: {}
    annotations: {}
    labels: {}
    resources: {}
    tolerations: []
  ports:
    health: "9090"
    webhook: "443"
  replicas: 3
  resourceNamePrefix: kubernetes-cluster-admission-controller
  webhookTimeoutSeconds: 3
  webhookFailurePolicy: Ignore
  webhookMatchConditions: []
  webhookServiceName: kubernetes-cluster-admission-controller-service
  webhookServerCertificateAuthorityName: tenable-cloud-security-kubernetes-cluster-admission-controller