apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tes-operator.fullname" . }}
  labels:
    {{- include "tes-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tes-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.operator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tes-operator.labels" . | nindent 8 }}
	{{- with .Values.operator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.operator.image.imagePullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tes-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          {{ if .Values.operator.image.registry }}
          image: "{{.Values.operator.image.registry}}/{{ .Values.operator.image.name }}:{{ .Values.operator.image.tag }}"
          {{ else }}
          image: "{{ .Values.operator.image.name }}:{{ .Values.operator.image.tag }}"
          {{ end }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.operator.service.port }}
              protocol: TCP
          livenessProbe: null
          readinessProbe: null
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          {{- with .Values.operator.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.operator.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tes.blades.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tes.blades.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tes.blades.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
