{{/*
Validate that the TES license and postgres DB are set in the cluster before install.
*/}}

{{- $liveCluster := lookup "v1" "Namespace" "" .Release.Namespace -}}
{{- if $liveCluster -}}
  {{- if not (lookup "v1" "Secret" .Release.Namespace "tes-pg-secrets") -}}
  {{- fail (printf "Required secret 'tes-pg-secrets' not found in namespace '%s'. Please create it before installing TES. Follow this installation link for guidance: https://docs.tenable.com/enclave-security/Content/install.htm#install" .Release.Namespace) -}}
  {{- end -}}

  {{- if not (lookup "v1" "Secret" .Release.Namespace "tes-license") -}}
  {{- fail (printf "Required secret 'tes-license' not found in namespace '%s'. Please create it before installing TES. Follow this installation link for guidance: https://docs.tenable.com/enclave-security/Content/install.htm#install" .Release.Namespace) -}}
  {{- end -}}
{{- end -}}
