{{- if .Values.connector.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "connector.labels" . | nindent 4 }}
  name: {{ include "connector.globalResourceName" (dict "name" "cr" "root" .) }}
rules:
  {{- if .Values.connector.clusterRoleExplicitPermissions }}
  - apiGroups: [""]
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - nodes/status
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - podtemplates
      - replicationcontrollers
      - resourcequotas
      - serviceaccounts
      - services
      - services/status
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - admissionregistration.k8s.io
      - apiextensions.k8s.io
      - apiregistration.k8s.io
      - apps
      - autoscaling
      - batch
      - discovery.k8s.io
      - events.k8s.io
      - extensions
      - networking.k8s.io
      - policy
      - rbac.authorization.k8s.io
      - storage.k8s.io
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  {{- else }}
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  {{- end }}
{{- end }}