apiVersion: v2
description: "DEPRECATED: This chart is no longer maintained. Please migrate to Tenable Enclave Security (https://docs.tenable.com/enclave-security/Content/install.htm)."
deprecated: true
type: application
home: https://www.tenable.com
sources:
  - https://github.com/tenable/helm-charts
maintainers:
  - name: Tenable SecurityCenter
    email: securitycenter@tenable.com
name: securitycenter
appVersion: "6.6.0"
version: 1.5.1