{{- if .Values.configureAdmissionController }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "admissionController.annotations" . | nindent 4 }}
  labels:
    {{- include "admissionController.labels" . | nindent 4 }}
  name: {{ .Values.admissionController.resourceNamePrefix }}-certificate-secret
  namespace: {{ .Release.Namespace }}
{{- end }}