{{- if and .Values.configureAdmissionController (not .Values.admissionController.webhookUrl) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "admissionController.annotations" . | nindent 4 }}
  labels:
    {{- include "admissionController.labels" . | nindent 4 }}
  name: {{ .Values.admissionController.resourceNamePrefix }}-service-account
  namespace: {{ .Release.Namespace }}
{{- end }}