# Default values for tes-operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

operator:
  nameOverride: ""
  fullnameOverride: ""
  image:
    name: tes-operator
    pullPolicy: IfNotPresent
    tag: "1.6.0-IA-13AUG25-1"
    imagePullSecret: ""
    registry: "tenable"
  helm:
    repo: "local"
    username: ""
    password: ""

  volumes:
    - name: tes-config-volume
      configMap:
        name: tes-operator-config
    - name: tes-blade-config-volume
      configMap:
        name: tes-blade-configs
    - name: secrets-volume
      secret:
        secretName: tes-operator-secrets

  volumeMounts:
    - name: tes-config-volume
      mountPath: /etc/tes-operator-config
      readOnly: true
    - name: tes-blade-config-volume
      mountPath: /etc/tes-blade-configs
      readOnly: true
    - name: secrets-volume
      mountPath: /etc/tes-operator-secrets
      readOnly: true

  resources: { }
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  podAnnotations: { }
  podLabels: { }

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  service:
    type: ClusterIP
    port: 80

tes:
  version: "2.0.4"
  blades:
    securitycenter:
    container-security:
    global:
      # scopeCluster: true for backwards compatibility with existing deployments
      scopeCluster: true
      useCustomCA: false
      # customCAIssuerName: {custom cert-manager issuer name}
      customCAIssuerKind: Issuer
      nodeSelector: { }
      tolerations: [ ]
      affinity:
      url:
      registry: tenable

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "tes-operator-sa"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

securityContext:
  runAsUser: 2001
  runAsGroup: 3000
