apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "manager.labels" . | nindent 4 }}
  name: {{ include "manager.resourceNamePrefix" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "manager.resourceNamePrefix" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "manager.resourceNamePrefix" . }}-service-account
  namespace: {{ .Release.Namespace }}