{{- if .Values.edgeCases.customErrors.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: custom-errors
  namespace: {{ .Release.Namespace }}
spec:
  errors:
    status:
      - "500-599"
    service:
      name: {{ .Values.edgeCases.customErrors.service }}
      port: 80
    query: {{ .Values.edgeCases.customErrors.query }}
{{- end }}
