{{- if and .Values.ingressRoutes.containerSecurity.enabled .Values.ingressRoutes.containerSecurity.internal.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoutes.containerSecurity.internal.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: ingressroute
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    {{- if .Values.ingressRoutes.containerSecurity.internal.dedicatedPort.enabled }}
    - consec-scanner
    {{- else }}
    - https
    {{- end }}
  routes:
    - match: PathPrefix("{{ .Values.ingressRoutes.containerSecurity.internal.pathPrefix }}")
      kind: Rule
      priority: {{ .Values.ingressRoutes.containerSecurity.internal.priority }}
      middlewares:
        {{- if .Values.ingressRoutes.containerSecurity.internal.ipWhitelist.enabled }}
        - name: consec-internal-ipwhitelist
        {{- end }}
        - name: security-headers
        {{- if .Values.rateLimit.enabled }}
        - name: {{ .Values.rateLimit.scanner.name | default "tes-scanner-rate-limit" }}
        {{- end }}
        {{- if .Values.edgeCases.conditionalHeaders.enabled }}
        - name: remove-range-headers
        {{- end }}
      services:
        - name: {{ .Values.ingressRoutes.containerSecurity.service }}
          port: {{ .Values.ingressRoutes.containerSecurity.port }}
          scheme: https
          serversTransport: {{ .Release.Namespace }}-{{- if eq .Values.defaultTransport "mtls" }}{{ .Values.serversTransports.mtls.name }}{{- else }}{{ .Values.serversTransports.insecureSkipVerify.name }}{{- end }}
  tls:
    secretName: {{ .Values.certificates.external.secretName }}
{{- end }}
