{{- if and .Values.ingressRoutes.licensing.enabled (include "tes-traefik.domain" .) }}
---
# IngressRoute for licensing service
# Routes: /tes/gateway/blades/platform/ls/* → tes-licensing-service:8092/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoutes.licensing.name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - https
  routes:
    - match: Host("{{ include "tes-traefik.domain" . }}") && PathPrefix("/tes/gateway/blades/platform/ls/")
      kind: Rule
      priority: {{ .Values.ingressRoutes.licensing.priority }}
      middlewares:
        - name: security-headers
        - name: strip-platform-licensing-prefix
      services:
        - name: {{ .Values.ingressRoutes.licensing.service }}
          port: {{ .Values.ingressRoutes.licensing.port }}
          scheme: https
          serversTransport: {{ .Release.Namespace }}-{{- if eq .Values.defaultTransport "mtls" }}{{ .Values.serversTransports.mtls.name }}{{- else }}{{ .Values.serversTransports.insecureSkipVerify.name }}{{- end }}
  tls:
    secretName: {{ .Values.certificates.external.secretName | quote }}
{{- end }}
