{{- if and .Values.ingressRoutes.containerSecurity.enabled .Values.ingressRoutes.containerSecurity.public.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoutes.containerSecurity.public.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: ingressroute
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    {{- range .Values.ingressRoutes.containerSecurity.public.entrypoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: PathPrefix("{{ .Values.ingressRoutes.containerSecurity.public.pathPrefix }}")
      kind: Rule
      priority: {{ .Values.ingressRoutes.containerSecurity.public.priority }}
      middlewares:
        - name: security-headers
        {{- if .Values.rateLimit.enabled }}
        - name: {{ .Values.rateLimit.api.name | default "tes-api-rate-limit" }}
        {{- end }}
      services:
        - name: {{ .Values.ingressRoutes.containerSecurity.service }}
          port: {{ .Values.ingressRoutes.containerSecurity.port }}
          scheme: https
          serversTransport: {{ .Release.Namespace }}-{{- if eq .Values.defaultTransport "mtls" }}{{ .Values.serversTransports.mtls.name }}{{- else }}{{ .Values.serversTransports.insecureSkipVerify.name }}{{- end }}
  tls:
    secretName: {{ .Values.certificates.external.secretName }}
{{- end }}
