{{- if and .Values.ingressRoutes.containerSecurity.enabled .Values.ingressRoutes.containerSecurity.internal.ipWhitelist.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: consec-internal-ipwhitelist
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: middleware
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ipWhiteList:
    sourceRange:
      {{- range .Values.ingressRoutes.containerSecurity.internal.ipWhitelist.sourceRange }}
      - {{ . }}
      {{- end }}
    # Return 403 Forbidden for IPs not in whitelist
{{- end }}
