{{- if .Values.serversTransports.insecureSkipVerify.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.serversTransports.insecureSkipVerify.name }}
  namespace: {{ .Release.Namespace }}
spec:
  insecureSkipVerify: true
{{- end }}
